In [36]:
print("Hello world") # test 

Hello world


Required Libraries 

In [37]:
!pip install numpy
!pip install pandas 

In [38]:
import numpy as np
import pandas as pd


In [39]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) #Loading values 

In [40]:
print(arr.shape)

(2, 3)


In [41]:
print(arr[1, 2])       # 6

6


In [42]:
print(arr[:, 1])   

[2 5]


Loading two new values

In [55]:
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6], [5, 6, 7]])
arr2 = np.array([[1, 2, 3], [4, 5, 6], [5, 6, 7]])
result = arr1+arr2
print(result)

[[ 2  4  6]
 [ 8 10 12]
 [10 12 14]]


Mathmatical and logical operation 

In [57]:
result = arr1+arr2
print (result)

[[ 2  4  6]
 [ 8 10 12]
 [10 12 14]]


In [59]:
#Matrix Multiplication
mul_result=arr1*arr2
print(mul_result)

[[ 1  4  9]
 [16 25 36]
 [25 36 49]]


In [45]:
arr3 = np.array([[7, 8, 9], [1, 2, 3], [4, 5, 6]])
arr4 = np.array([[0, 1, 0], [1, 0, 1], [0, 1, 0]])
result = arr3 + arr4  # Element-wise addition



In [60]:
print(result)

[[ 2  4  6]
 [ 8 10 12]
 [10 12 14]]


Dot Product 

In [47]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.dot(a, b))  # 32


32


cross Product 

In [48]:
print(np.cross(a,b))

[-3  6 -3]


Filtering the innner values of matrix 

In [49]:
arr = np.array([10, 20, 30, 40])
print(arr[arr > 25])  # [30 40]


[30 40]


In [50]:
arr = np.array([40, 50, 70, 40])
print(arr[arr > 25])  # [30 40]


[40 50 70 40]


some special mathmatical operations (sum, standrad deviations, maximum from 

In [61]:
x = np.array([1, 2, 3, 4])

print(np.sum(x))       # 10
print(np.mean(x))      # 2.5
print(np.std(x))       # Standard deviation
print(np.max(x))       # 4
print(np.min(x))       # 1
print(np.exp(x))       # e^x
print(np.log(x))       # natural log

10
2.5
1.118033988749895
4
1
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]


Where function in numpy

In [62]:
x = np.array([1, 2, 3, 4, 5])
np.where(x > 3, 100, 0)  


array([  0,   0,   0, 100, 100])

In [63]:
x = np.array([5, 100 ,600, 700, 500])
np.where(x > 29, 100, 0)  


array([  0, 100, 100, 100, 100])