In [6]:
import numpy as np
import pandas as pd
from pathlib import Path
DATA_DIR = Path("/kaggle/input")

In [9]:
df = pd.read_csv("heart_disease_uci.csv")

In [10]:
df.head()

id  age     sex    dataset               cp  trestbps   chol    fbs  \
0   1   63    Male  Cleveland   typical angina     145.0  233.0   True   
1   2   67    Male  Cleveland     asymptomatic     160.0  286.0  False   
2   3   67    Male  Cleveland     asymptomatic     120.0  229.0  False   
3   4   37    Male  Cleveland      non-anginal     130.0  250.0  False   
4   5   41  Female  Cleveland  atypical angina     130.0  204.0  False   

          restecg  thalch  exang  oldpeak        slope   ca  \
0  lv hypertrophy   150.0  False      2.3  downsloping  0.0   
1  lv hypertrophy   108.0   True      1.5         flat  3.0   
2  lv hypertrophy   129.0   True      2.6         flat  2.0   
3          normal   187.0  False      3.5  downsloping  0.0   
4  lv hypertrophy   172.0  False      1.4    upsloping  0.0   

                thal  num  
0       fixed defect    0  
1             normal    2  
2  reversable defect    1  
3             normal    0  
4             normal    0

In [50]:
df.isna().sum().sort_values(ascending=False)

ca                          611
oldpeak                      62
trestbps                     59
thalch                       55
chol                         30
age                           0
cp_typical angina             0
thal_normal                   0
slope_upsloping               0
slope_flat                    0
exang_True                    0
restecg_st-t abnormality      0
restecg_normal                0
fbs_True                      0
dataset_VA Long Beach         0
cp_non-anginal                0
cp_atypical angina            0
sex                           0
dataset_Switzerland           0
dataset_Hungary               0
target                        0
Gender_1                      0
thal_reversable defect        0
dtype: int64

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   age                       920 non-null    int64  
 1   sex                       920 non-null    int64  
 2   trestbps                  861 non-null    float64
 3   chol                      890 non-null    float64
 4   thalch                    865 non-null    float64
 5   oldpeak                   858 non-null    float64
 6   ca                        309 non-null    float64
 7   Gender_1                  920 non-null    int32  
 8   target                    920 non-null    int32  
 9   dataset_Hungary           920 non-null    bool   
 10  dataset_Switzerland       920 non-null    bool   
 11  dataset_VA Long Beach     920 non-null    bool   
 12  cp_atypical angina        920 non-null    bool   
 13  cp_non-anginal            920 non-null    bool   
 14  cp_typical

In [53]:
df.describe()

age         sex    trestbps        chol      thalch     oldpeak  \
count  920.000000  920.000000  861.000000  890.000000  865.000000  858.000000   
mean    53.510870    0.789130  132.132404  199.130337  137.545665    0.878788   
std      9.424685    0.408148   19.066070  110.780810   25.926276    1.091226   
min     28.000000    0.000000    0.000000    0.000000   60.000000   -2.600000   
25%     47.000000    1.000000  120.000000  175.000000  120.000000    0.000000   
50%     54.000000    1.000000  130.000000  223.000000  140.000000    0.500000   
75%     60.000000    1.000000  140.000000  268.000000  157.000000    1.500000   
max     77.000000    1.000000  200.000000  603.000000  202.000000    6.200000   

               ca    Gender_1      target  
count  309.000000  920.000000  920.000000  
mean     0.676375    0.789130    0.553261  
std      0.935653    0.408148    0.497426  
min      0.000000    0.000000    0.000000  
25%      0.000000    1.000000    0.000000  
50%      0.000000    1.000000    1.000000  
75%      1.000000    1.000000    1.000000  
max      3.000000    1.000000    1.000000

In [54]:
df.corr()

age       sex  trestbps      chol    thalch  \
age                       1.000000  0.056889  0.244253 -0.086234 -0.365778   
sex                       0.056889  1.000000  0.001087 -0.197281 -0.179320   
trestbps                  0.244253  0.001087  1.000000  0.092853 -0.104899   
chol                     -0.086234 -0.197281  0.092853  1.000000  0.236121   
thalch                   -0.365778 -0.179320 -0.104899  0.236121  1.000000   
oldpeak                   0.258243  0.103930  0.161908  0.047734 -0.151174   
ca                        0.370416  0.094123  0.093705  0.051606 -0.264094   
Gender_1                  0.056889  1.000000  0.001087 -0.197281 -0.179320   
target                    0.282700  0.307284  0.106233 -0.230583 -0.394503   
dataset_Hungary          -0.407613 -0.109900  0.017296  0.310879  0.039312   
dataset_Switzerland       0.075329  0.124779 -0.040867 -0.720231 -0.250034   
dataset_VA Long Beach     0.326713  0.233686  0.038370 -0.096880 -0.257568   
cp_atypical angina       -0.218902 -0.165400 -0.046263  0.149084  0.251270   
cp_non-anginal           -0.010060 -0.064031 -0.041922 -0.007507  0.144490   
cp_typical angina         0.032032 -0.003668  0.047096  0.016731  0.104430   
fbs_True                  0.219915  0.075370  0.160424  0.091077 -0.032594   
restecg_normal           -0.226844 -0.015282 -0.116172 -0.039022  0.014002   
restecg_st-t abnormality  0.137748  0.065599  0.088758 -0.135697 -0.152356   
exang_True                0.160910  0.155204  0.152328 -0.031898 -0.356439   
slope_flat                0.121025  0.020640  0.061531 -0.021081 -0.238112   
slope_upsloping          -0.011606 -0.091201 -0.068574 -0.006000  0.315084   
thal_normal              -0.016946 -0.290692 -0.038805  0.110957  0.281479   
thal_reversable defect    0.131164  0.127775  0.081310 -0.077663 -0.090273   

                           oldpeak        ca  Gender_1    target  \
age                       0.258243  0.370416  0.056889  0.282700   
sex                       0.103930  0.094123  1.000000  0.307284   
trestbps                  0.161908  0.093705  0.001087  0.106233   
chol                      0.047734  0.051606 -0.197281 -0.230583   
thalch                   -0.151174 -0.264094 -0.179320 -0.394503   
oldpeak                   1.000000  0.281817  0.103930  0.385528   
ca                        0.281817  1.000000  0.094123  0.455599   
Gender_1                  0.103930  0.094123  1.000000  0.307284   
target                    0.385528  0.455599  0.307284  1.000000   
dataset_Hungary          -0.191974 -0.071693 -0.109900 -0.263297   
dataset_Switzerland      -0.081958  0.126804  0.124779  0.301614   
dataset_VA Long Beach     0.182028 -0.058442  0.233686  0.203267   
cp_atypical angina       -0.259012 -0.158215 -0.165400 -0.403465   
cp_non-anginal           -0.114797 -0.127946 -0.064031 -0.209812   
cp_typical angina         0.039427 -0.041847 -0.003668 -0.054673   
fbs_True                  0.054841  0.141167  0.075370  0.108071   
restecg_normal           -0.116004 -0.141947 -0.015282 -0.097455   
restecg_st-t abnormality  0.050329  0.029461  0.065599  0.104750   
exang_True                0.391150  0.127385  0.155204  0.433605   
slope_flat                0.369258  0.166524  0.020640  0.339273   
slope_upsloping          -0.130493 -0.139348 -0.091201 -0.180903   
thal_normal              -0.132770 -0.249394 -0.290692 -0.269326   
thal_reversable defect    0.156792  0.206159  0.127775  0.257029   

                          dataset_Hungary  ...  cp_non-anginal  \
age                             -0.407613  ...       -0.010060   
sex                             -0.109900  ...       -0.064031   
trestbps                         0.017296  ...       -0.041922   
chol                             0.310879  ...       -0.007507   
thalch                           0.039312  ...        0.144490   
oldpeak                         -0.191974  ...       -0.114797   
ca                              -0.071693  ...       -0.127946 

In [26]:
df['sex'] = df['sex'].map({'Male': 1, 'Female': 0})

In [32]:
df['target'] = (df['num'] > 0).astype(int)
df.drop(columns=['num'], inplace=True)

In [34]:
df.drop(columns=['id'], inplace=True)

In [ ]:
df['target'] = (df['num'] > 0).astype(int)
df.drop(columns=['num'], inplace=True)

In [35]:
bool_cols = df.select_dtypes(include='bool').columns
df[bool_cols] = df[bool_cols].astype(int)

In [36]:
cat_cols = df.select_dtypes(include='object').columns
df = pd.get_dummies(df, columns=cat_cols, drop_first=True)

In [60]:
# another method
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='median')
X = imputer.fit_transform(X)


In [61]:
df.head()

age  sex  trestbps   chol  thalch  oldpeak   ca  Gender_1  target  \
0   63    1     145.0  233.0   150.0      2.3  0.0         1       0   
1   67    1     160.0  286.0   108.0      1.5  3.0         1       1   
2   67    1     120.0  229.0   129.0      2.6  2.0         1       1   
3   37    1     130.0  250.0   187.0      3.5  0.0         1       0   
4   41    0     130.0  204.0   172.0      1.4  0.0         0       0   

   dataset_Hungary  ...  cp_non-anginal  cp_typical angina  fbs_True  \
0            False  ...           False               True      True   
1            False  ...           False              False     False   
2            False  ...           False              False     False   
3            False  ...            True              False     False   
4            False  ...           False              False     False   

   restecg_normal  restecg_st-t abnormality  exang_True  slope_flat  \
0           False                     False       False       False   
1           False                     False        True        True   
2           False                     False        True        True   
3            True                     False       False       False   
4           False                     False       False       False   

   slope_upsloping  thal_normal  thal_reversable defect  
0            False        False                   False  
1            False         True                   False  
2            False        False                    True  
3            False         True                   False  
4             True         True                   False  

[5 rows x 23 columns]

In [63]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)


In [64]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [66]:
X

age  sex  trestbps   chol  thalch  oldpeak   ca  Gender_1  \
0     63    1     145.0  233.0   150.0      2.3  0.0         1   
1     67    1     160.0  286.0   108.0      1.5  3.0         1   
2     67    1     120.0  229.0   129.0      2.6  2.0         1   
3     37    1     130.0  250.0   187.0      3.5  0.0         1   
4     41    0     130.0  204.0   172.0      1.4  0.0         0   
..   ...  ...       ...    ...     ...      ...  ...       ...   
915   54    0     127.0  333.0   154.0      0.0  NaN         0   
916   62    1       NaN  139.0     NaN      NaN  NaN         1   
917   55    1     122.0  223.0   100.0      0.0  NaN         1   
918   58    1       NaN  385.0     NaN      NaN  NaN         1   
919   62    1     120.0  254.0    93.0      0.0  NaN         1   

     dataset_Hungary  dataset_Switzerland  ...  cp_non-anginal  \
0              False                False  ...           False   
1              False                False  ...           False   
2              False                False  ...           False   
3              False                False  ...            True   
4              False                False  ...           False   
..               ...                  ...  ...             ...   
915            False                False  ...           False   
916            False                False  ...           False   
917            False                False  ...           False   
918            False                False  ...           False   
919            False                False  ...           False   

     cp_typical angina  fbs_True  restecg_normal  restecg_st-t abnormality  \
0                 True      True           False                     False   
1                False     False           False                     False   
2                False     False           False                     False   
3                False     False            True                     False   
4                False     False           False                     False   
..                 ...       ...             ...                       ...   
915              False      True           False                      True   
916               True     False           False                      True   
917              False      True           False                      True   
918              False      True           False                     False   
919              False     False           False                     False   

     exang_True  slope_flat  slope_upsloping  thal_normal  \
0         False       False            False        False   
1          True        True            False         True   
2          True        True            False        False   
3         False       False            False         True   
4         False       False             True         True   
..          ...         ...              ...          ...   
915       False       False            False        False   
916       False       False            False        False   
917       False       False            False        False   
918       False       False            False        False   
919        True       False            False        False   

     thal_reversable defect  
0                     False  
1                     False  
2                      True  
3                     False  
4                     False  
..                      ...  
915                   False  
916                   False  
917                   False  
918                   False  
919                   False  

[920 rows x 22 columns]

In [67]:
y

0      0
1      1
2      1
3      0
4      0
      ..
915    1
916    0
917    1
918    0
919    1
Name: target, Length: 920, dtype: int32

In [65]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

print("Model trained successfully!")

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [8]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [9]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.9016393442622951
Accuracy of Decision Trees 0.8360655737704918


In [10]:
confusion_matrix(y_test,y_pred1)

array([[26,  6],
       [ 0, 29]])

In [11]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))

Logistic Regression Confusion Matrix



0   1
0  26   6
1   0  29

In [12]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))

Decision Tree Confusion Matrix



0   1
0  24   8
1   2  27

In [13]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pred1
result['Decision Tree Prediction'] = y_pred2

In [14]:
result.sample(10)

Actual Label  Logistic Regression Prediction  Decision Tree Prediction
257             0                               0                         0
65              1                               1                         1
164             1                               1                         1
29              1                               1                         1
296             0                               1                         0
184             0                               0                         0
161             1                               1                         1
292             0                               0                         0
53              1                               1                         1
147             1                               1                         1

In [15]:
from sklearn.metrics import recall_score,precision_score,f1_score

In [16]:
print("For Logistic regression Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred1))
print("Recall - ",recall_score(y_test,y_pred1))
print("F1 score - ",f1_score(y_test,y_pred1))

For Logistic regression Model
--------------------------------------------------
    0   1
0  26   6
1   0  29
--------------------------------------------------
Precision -  0.8285714285714286
Recall -  1.0
F1 score -  0.90625


In [17]:
print("For DT Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred2))
print("Recall - ",recall_score(y_test,y_pred2))
print("F1 score - ",f1_score(y_test,y_pred2))

For DT Model
--------------------------------------------------
    0   1
0  24   8
1   2  27
--------------------------------------------------
Precision -  0.7714285714285715
Recall -  0.9310344827586207
F1 score -  0.8437500000000001


In [18]:
precision_score(y_test,y_pred1,average=None)

array([1.        , 0.82857143])

In [19]:
precision_score(y_test,y_pred2,average=None)

array([0.92307692, 0.77142857])

In [21]:
recall_score(y_test,y_pred2,average=None)

array([0.75      , 0.93103448])